format = """
[î‚¶](#8B0000)\
$username$hostname\
[î‚°](bg:#B22222 fg:#8B0000)\
$directory\
[î‚°](fg:#B22222 bg:#CD5C5C)\
$git_branch$git_status\
[î‚°](fg:#CD5C5C bg:#A52A2A)\
$c$cpp$python\
[î‚°](fg:#A52A2A bg:#2F4F4F)\
$time\
[î‚°](fg:#2F4F4F) \
"""

[username]
show_always = true
style_user = "bg:#8B0000"
format = '[ï€‡ $user ]($style)'

[hostname]
ssh_only = false
style = "bg:#8B0000"
format = '[î©º $hostname ]($style)'

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
style = "bg:#B22222"
format = "[ ï¼ $path ]($style)"

[directory.substitutions]
"Documents" = "ğŸ“„"
"Downloads" = "ğŸ“¥"
"Music" = "ğŸœ"
"Pictures" = "ğŸ“·"

[git_branch]
style = "bg:#CD5C5C"
format = '[ îœ¥ $branch ]($style)'

[git_status]
style = "bg:#CD5C5C"
format = '[[($all_status$ahead_behind )](bg:#CD5C5C)]($style)'

[c]
style = "bg:#A52A2A"
format = '[ î˜ $version ]($style)'

[cpp]
style = "bg:#A52A2A"
format = '[ î™† $version ]($style)'

[python]
style = "bg:#A52A2A"
format = '[ îœ¼ ($version) ]($style)'

[time]
disabled = false
time_format = "%H:%M:%S"
style = "bg:#2F4F4F"
format = '[ ïº $time ]($style)'

